name: Validate Docker Compose

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          if [ ! -f .env ] && [ -f .env.example ]; then
            cp .env.example .env
          fi

          if [ ! -f stack.env ] && [ -f stack.env.example ]; then
            cp stack.env.example stack.env
          fi
      - run: docker compose config -q
